site_name: DPD Pāḷi Courses
docs_dir: docs
site_dir: site
theme:
  name: material
  language: en
  custom_dir: tools/ssg/stylesheets
  palette:
  - scheme: default
    primary: brown
    accent: orange
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode
  - scheme: slate
    primary: brown
    accent: orange
    toggle:
      icon: material/brightness-4
      name: Switch to light mode
  features:
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.top
  - navigation.indexes
  - content.code.copy
extra_css:
- dpd.css
- dpd-variables.css
- extra.css
extra_javascript:
- footnotes.js
markdown_extensions:
- attr_list
- toc:
    permalink: true
    baselevel: 2
- pymdownx.highlight:
    anchor_linenums: true
- pymdownx.inlinehilite
- pymdownx.snippets
- pymdownx.superfences
- tables
- md_in_html
hooks:
- tools/ssg/scripts/footnote_hook.py
nav:
- Home: index.md
- About: about.md
- Literature: literature.md
- Beginner Course (BPC):
  - Lessons:
    - Lessons Index: bpc/index.md
    - Class 1: bpc/class_1/index.md
    - Class 2:
      - Index: bpc/class_2/index.md
      - Review: bpc/class_2/1_review.md
      - The Alphabet & Pronunciation: bpc/class_2/2_alphabet.md
      - Declension of Nouns: bpc/class_2/3_decl_nouns.md
      - How to do the exercises: bpc/class_2/4_home_work.md
    - Class 3:
      - Index: bpc/class_3/index.md
      - Review: bpc/class_3/1_review.md
      - Conjugation of Verbs: bpc/class_3/2_conjug.md
      - 3_Preset: bpc/class_3/3_preset.md
      - Imperative Verbs!: bpc/class_3/4_imper.md
      - Verbal roots (dhātu): bpc/class_3/5_roots.md
      - Root Group 1 - bhūvādigaṇa: bpc/class_3/6_root_1.md
      - Root Group 4 - svādigaṇa: bpc/class_3/7_root_4.md
      - Root Group 5 - kiyādigaṇa: bpc/class_3/8_root_5.md
      - Root Group 6 - gahādigaṇa: bpc/class_3/9_root_6.md
      - Root Group 8 - curādigaṇa: bpc/class_3/10_root_8.md
      - Historical Present: bpc/class_3/11_histor_pr.md
      - Some things that will help you when doing the exercises: bpc/class_3/12_help_with_ex.md
      - Some tricky bases: bpc/class_3/13_tricky_base.md
      - Extra Reading: bpc/class_3/14_home_work.md
    - Class 4:
      - Index: bpc/class_4/index.md
      - Review: bpc/class_4/1_review.md
      - How to use DPR: bpc/class_4/2_dpr_tpr.md
      - Different systems of root groups: bpc/class_4/3_var_root_group.md
      - avuddhika / guṇa / vuḍḍhi: bpc/class_4/4_vuddhi.md
      - Root Group 2 - rudhādigaṇa: bpc/class_4/5_root_2.md
      - Root Group 3 – divādigaṇa: bpc/class_4/6_root_3.md
      - Some Basic Sandhi – The Assimilation of the Letter y: bpc/class_4/7_basic_assim.md
      - Root Group 7 – tanādigaṇa: bpc/class_4/8_root_7.md
      - Masculine Noun ending in -i: bpc/class_4/9_masc_i.md
      - The Aorist or Past Tense (ajjatanī): bpc/class_4/10_aor.md
      - Homeless work: bpc/class_4/13_home_work.md
    - Class 5:
      - Index: bpc/class_5/index.md
      - Review: bpc/class_5/1_review.md
      - Personal Pronouns: bpc/class_5/2_pers_pron.md
      - Future Tense: bpc/class_5/3_future.md
      - Masculine nouns ending in -ī: bpc/class_5/4_masc_ii.md
      - Intransitive, Transitive and di-transitive verbs: bpc/class_5/5_trans.md
      - How to say No!: bpc/class_5/6_say_no.md
      - With & together with “saddhiṃ” and “saha”: bpc/class_5/7_with.md
      - Homeless work: bpc/class_5/8_home_work.md
      - Some important lists to have at hand: bpc/class_5/del.md
    - Class 6:
      - Index: bpc/class_6/index.md
      - Review: bpc/class_6/1_review.md
      - Masculine nouns ending in -u: bpc/class_6/2_masc_u.md
      - Masculine nouns ending in -ū: bpc/class_6/3_masc_uu.md
      - Substantives (guṇanāma): bpc/class_6/4_subst.md
      - Conjunction “ca”: bpc/class_6/5_and_or.md
      - Adverbs of time: bpc/class_6/6_adv_time.md
      - Homeless work: bpc/class_6/7_home_work.md
    - Class 7:
      - Index: bpc/class_7/index.md
      - Feminine Nouns ending in -ā: bpc/class_7/2_fem_aa.md
      - Optative or Potential Verbs (sattamī): bpc/class_7/3_opt.md
      - Traditional Pāli Root lists: bpc/class_7/4_pali_lists.md
      - Homeless work: bpc/class_7/5_home_work.md
    - Class 8:
      - Index: bpc/class_8/index.md
      - Review: bpc/class_8/1_review.md
      - Absolutive / Gerund / Indeclinable Past Participle (pubbakiriyā): bpc/class_8/2_abs_ger.md
      - Feminine Nouns: bpc/class_8/3_fem.md
      - Adverbs of place: bpc/class_8/4_adv_place.md
      - Homeless work: bpc/class_8/5_home_work.md
    - Class 9:
      - Index: bpc/class_9/index.md
      - Review: bpc/class_9/1_review.md
      - Neuter Nouns: bpc/class_9/2_nt.md
      - The Infinitive (tumanta): bpc/class_9/3_inf.md
      - The dative of purpose: bpc/class_9/4_dat_purpose.md
      - yāva … tāva: bpc/class_9/5_yava_tava.md
      - How to ask a question with Adverbs & Indeclinable: bpc/class_9/6_adv_inter.md
      - Homeless work: bpc/class_9/7_home_work.md
    - Class 10:
      - Index: bpc/class_10/index.md
      - Review: bpc/class_10/1_review.md
      - Present Participle (missakiriya): bpc/class_10/2_prp.md
      - Pronouns (sabbanāma): bpc/class_10/3_pron.md
      - Definite and indefinite article: bpc/class_10/4_article.md
      - Emphatic particle: bpc/class_10/5_emph.md
      - Locative Absolute: bpc/class_10/6_loc_gen_abs.md
      - Homeless work: bpc/class_10/7_home_work.md
    - Class 11:
      - Index: bpc/class_11/index.md
      - Review: bpc/class_11/1_review.md
      - (Passive) Past Participles: bpc/class_11/2_pp.md
      - Adjectives (guṇanāma, guṇavacana, visesana): bpc/class_11/3_adj.md
      - Ablative of Separation: bpc/class_11/4_abl_sep.md
      - Homeless work: bpc/class_11/5_home_work.md
    - Class 12:
      - Index: bpc/class_12/index.md
      - Review: bpc/class_12/1_review.md
      - Numbers (*saṅkhyā*): bpc/class_12/2_numb.md
      - Cardinal Numbers (saṅkhyā-padhāna): bpc/class_12/3_card.md
      - Ordinal Numbers (saṅkhyā-pūraṇa): bpc/class_12/4_ordin.md
      - Kahāpaṇāna![](../../assets/images/kahapana.png): bpc/class_12/5_kahap.md
      - Homeless work: bpc/class_12/6_home_work.md
    - Class 13:
      - Index: bpc/class_13/index.md
      - Review: bpc/class_13/1_review.md
      - Adverbs: bpc/class_13/2_adv.md
      - Passive Verbs: bpc/class_13/3_pass_verb.md
      - Passive Present Participles (pprp): bpc/class_13/4_pprp.md
      - Homeless work: bpc/class_13/5_home_work.md
    - Class 14:
      - Index: bpc/class_14/index.md
      - Review: bpc/class_14/1_review.md
      - Causative Verbs: bpc/class_14/2_caus_verb.md
      - Causative Passive Verbs: bpc/class_14/3_caus_pass.md
      - Potential Participle (ptp): bpc/class_14/4_ptp.md
      - Homeless work: bpc/class_14/5_home_work.md
  - Exercises:
    - Index: bpc_ex/index.md
    - Class 1 Exercises: bpc_ex/1_class.md
    - Class 2 Exercises: bpc_ex/2_class.md
    - Class 3 Exercises: bpc_ex/3_class.md
    - Class 4 Exercises: bpc_ex/4_class.md
    - Class 5 Exercises: bpc_ex/5_class.md
    - Class 6 Exercises: bpc_ex/6_class.md
    - Class 7 Exercises: bpc_ex/7_class.md
    - Class 8 Exercises: bpc_ex/8_class.md
    - Class 9 Exercises: bpc_ex/9_class.md
    - Class 10 Exercises: bpc_ex/10_class.md
    - Class 11 Exercises: bpc_ex/11_class.md
    - Class 12 Exercises: bpc_ex/12_class.md
    - Class 13 Exercises: bpc_ex/13_class.md
    - Class 14 Exercises: bpc_ex/14_class.md
    - Class 15: bpc_ex/15_class.md
  - Answer Keys:
    - Index: bpc_key/index.md
    - Class 1 Exercises: bpc_key/1_class.md
    - Class 2 Exercises: bpc_key/2_class.md
    - Class 3 Exercises: bpc_key/3_class.md
    - Class 4 Exercises: bpc_key/4_class.md
    - Class 5 Exercises: bpc_key/5_class.md
    - Class 6 Exercises: bpc_key/6_class.md
    - Class 7 Exercises: bpc_key/7_class.md
    - Class 8 Exercises: bpc_key/8_class.md
    - Class 9 Exercises: bpc_key/9_class.md
    - Class 10 Exercises: bpc_key/10_class.md
    - Class 11 Exercises: bpc_key/11_class.md
    - Class 12 Exercises: bpc_key/12_class.md
    - Class 13 Exercises: bpc_key/13_class.md
    - Class 14 Exercises: bpc_key/14_class.md
    - Class 15: bpc_key/15_class.md
- Intermediate Course (IPC):
  - Lessons:
    - Lessons Index: ipc/index.md
    - Class 16:
      - Index: ipc/class_16/index.md
      - Sandhi: ipc/class_16/1_sandhi.md
      - Vowel Sandhi *(sara-sandhi)*: ipc/class_16/2_vowel.md
      - Elision of a Vowel: ipc/class_16/3_vowel_1.md
      - Possibility \#2: ipc/class_16/4_vowel_2.md
      - Lengthening of a Vowel: ipc/class_16/5_vowel_3.md
      - Possibility \#4: ipc/class_16/6_vowel_4.md
      - Vowel Changes: ipc/class_16/7_vowel_5.md
      - Possibility \#6: ipc/class_16/8_vowel_6.md
      - Possibility \#7: ipc/class_16/9_vowel_7.md
      - Consonant Insertions: ipc/class_16/10_vowel_8.md
      - Possibility \#9: ipc/class_16/11_vowel_9.md
      - Vowel Sandhi Reference Table: ipc/class_16/12_vowel_ref_table.md
      - Homeless work: ipc/class_16/13_home_work.md
    - Class 17:
      - Index: ipc/class_17/index.md
      - Pāli Alphabet Analysis: ipc/class_17/1_alphabet_analys.md
      - Consonant Sandhi (*vyañjana-sandhi)*: ipc/class_17/2_cons.md
      - Possibility \#1: ipc/class_17/3_cons_1.md
      - Possibility \#2: ipc/class_17/4_cons_2.md
      - Possibility \#3: ipc/class_17/5_cons_3.md
      - Possibility \#4: ipc/class_17/6_cons_4.md
      - Possibility \#5: ipc/class_17/7_cons_5.md
      - Niggahīta Sandhi: ipc/class_17/8_nig_1.md
      - Possibility \#2: ipc/class_17/9_nig_2.md
      - Possibility \#3: ipc/class_17/10_nig_3.md
      - Possibility \#4: ipc/class_17/11_nig_4.md
      - Possibility \#5: ipc/class_17/12_nig_5.md
      - Possibility \#6: ipc/class_17/13_nig_6.md
      - Possibility \#7: ipc/class_17/14_nig_7.md
      - Possibility \#8: ipc/class_17/15_nig_8.md
      - Possibility \#9: ipc/class_17/16_nig_9.md
      - Possibility \#10: ipc/class_17/17_nig_10.md
      - 'Please deconstruct the following:': ipc/class_17/18_ex.md
      - Homeless work: ipc/class_17/19_home_work.md
    - Class 18:
      - Index: ipc/class_18/index.md
      - Phonetic Changes: ipc/class_18/1_phonetic.md
      - Phonetic changes: ipc/class_18/2_as_ya.md
      - Phonetic changes of -t-: ipc/class_18/3_as_ta.md
      - Phonetic changes of -n-: ipc/class_18/4_as_na.md
      - Phonetic changes of -s-: ipc/class_18/5_as_sa.md
      - 6_As_Sum: ipc/class_18/6_as_sum.md
      - Mixed Sandhi (vomissaka-sandhi): ipc/class_18/7_mix_san.md
      - Another consonant assimilation: ipc/class_18/8_as_misc.md
      - 9_Ex: ipc/class_18/9_ex.md
      - Some Irregular Masculine Nouns: ipc/class_18/10_irreg_masc.md
      - 11_Ex: ipc/class_18/11_ex.md
      - Homeless work: ipc/class_18/home_work.md
    - Class 19:
      - Index: ipc/class_19/index.md
      - Compounds (*samāsa)*: ipc/class_19/1_comp.md
      - Kammadhāraya or Adjectival Compounds: ipc/class_19/2_kamm.md
      - Digu-samāsa or Numerical Compounds: ipc/class_19/3_digu.md
      - Tappurisa-samāsa or Case Compounds: ipc/class_19/4_tap.md
      - Dvanda Samāsa: ipc/class_19/5_dvanda.md
      - General “Rules” for Compounds: ipc/class_19/6_comp_rules.md
      - 7_Ex: ipc/class_19/7_ex.md
      - Homeless work: ipc/class_19/8_home_work.md
    - Class 20:
      - Index: ipc/class_20/index.md
      - Abyayībhāva-samāsa or Adverbial Compounds: ipc/class_20/1_abya.md
      - Bahubbīhi-samāsa or Attributive Compounds: ipc/class_20/2_bahub.md
      - Missaka-samāsa or Complex Compounds: ipc/class_20/3_mis.md
      - Changes Of Certain Words In Compounds: ipc/class_20/4_change_comp.md
      - 5_Ex: ipc/class_20/5_ex.md
      - Homeless work: ipc/class_20/6_home_work.md
    - Class 21:
      - Index: ipc/class_21/index.md
      - Revision of Verbs: ipc/class_21/1_revision.md
      - 'Three Voices: Active, Reflexive and Passive': ipc/class_21/2_voices.md
      - Passive Reflexive: ipc/class_21/3_pass_refl.md
      - Present Tense (*vattamānā*): ipc/class_21/4_pres.md
      - Imperative (*pañcamī*): ipc/class_21/5_imp.md
      - Optative (*sattamī*): ipc/class_21/6_opt.md
      - Perfect Past Tense (*parokkhā*): ipc/class_21/7_perf.md
      - Imperfect Past Tense (*hiyyattanī*): ipc/class_21/8_imperf.md
      - Aorist (*ajjatanī*): ipc/class_21/9_aor.md
      - Summary of Parassapada & Attanopada Conjugations: ipc/class_21/10_sum.md
      - Homeless work: ipc/class_21/11_home_work.md
    - Class 22:
      - Index: ipc/class_22/index.md
      - Future Tense (*bhavissantī*): ipc/class_22/1_fut.md
      - Conditional Tense (*kālātipatti*): ipc/class_22/2_cond.md
      - The 8 Root Groups[^13]: ipc/class_22/3_root_groups.md
      - Irregular Verbal Bases: ipc/class_22/4_irreg_base.md
      - Homeless work: ipc/class_22/5_home_work.md
    - Class 23:
      - Index: ipc/class_23/index.md
      - Prefixes (upasagga): ipc/class_23/1_prefix.md
      - 2_Aa: ipc/class_23/2_aa.md
      - 3_Ati: ipc/class_23/3_ati.md
      - 4_Adhi: ipc/class_23/4_adhi.md
      - 5_Anu: ipc/class_23/5_anu.md
      - 6_Apa: ipc/class_23/6_apa.md
      - 7_Api: ipc/class_23/7_api.md
      - 8_Abhi: ipc/class_23/8_abhi.md
      - 9_Ava: ipc/class_23/9_ava.md
      - 10_Ud: ipc/class_23/10_ud.md
      - 11_Upa: ipc/class_23/11_upa.md
      - 12_Ni: ipc/class_23/12_ni.md
      - 13_Nii: ipc/class_23/13_nii.md
      - 14_Pa: ipc/class_23/14_pa.md
      - 15_Pati: ipc/class_23/15_pati.md
      - 16_Para: ipc/class_23/16_para.md
      - 17_Pari: ipc/class_23/17_pari.md
      - 18_Vi: ipc/class_23/18_vi.md
      - 19_Sam: ipc/class_23/19_sam.md
      - 20_Mixed_Pref: ipc/class_23/20_mixed_pref.md
      - Some Adverbs (nipāta) used as Prefixes: ipc/class_23/21_nipata.md
      - dur, su, nir & etc.: ipc/class_23/22_dur_su_nir.md
    - Class 24:
      - Index: ipc/class_24/index.md
      - Passive Verbs: ipc/class_24/1_pass.md
      - Irregular Passive Bases: ipc/class_24/2_irreg_pass.md
      - Causative Verbs: ipc/class_24/3_caus.md
      - Irregular Causative Bases: ipc/class_24/4_irreg_caus.md
      - Causative Passive Verbs: ipc/class_24/5_caus_pass.md
      - Active Past Participle: ipc/class_24/6_app.md
      - Homeless work: ipc/class_24/7_home_work.md
    - Class 25:
      - Index: ipc/class_25/index.md
      - Derivatives: ipc/class_25/1_deriv.md
      - Types of nouns: ipc/class_25/2_nouns.md
      - Anubandha: ipc/class_25/3_anub.md
      - Secondary Derivatives (taddhita): ipc/class_25/4_taddh.md
      - \*a (dyed with): ipc/class_25/5_taddh_2.md
      - Homeless work: ipc/class_25/6_home_work.md
    - Class 26:
      - Index: ipc/class_26/index.md
      - More Secondary Derivatives: ipc/class_26/1_having.md
      - Numerical (saṅkhyātaddhita): ipc/class_26/2_numer.md
      - State of Being (bhāvataddhita): ipc/class_26/3_state.md
      - Indeclinable (abyayataddhita): ipc/class_26/4_ind.md
      - Homeless work: ipc/class_26/5_home_work.md
    - Class 27:
      - Index: ipc/class_27/index.md
      - Primary Derivatives (kitaka): ipc/class_27/1_kitaka.md
      - Kicca: ipc/class_27/2_kicca.md
      - Kita: ipc/class_27/3_kita.md
      - Homeless work: ipc/class_27/4_home_work.md
    - Class 28:
      - Index: ipc/class_28/index.md
      - More Primary Derivatives: ipc/class_28/1_kita_1.md
      - tar: ipc/class_28/2_kita_less.md
      - Homeless work: ipc/class_28/3_home_work.md
  - Exercises:
    - Index: ipc_ex/index.md
    - Class 16: ipc_ex/16_class.md
    - Class 17: ipc_ex/17_class.md
    - Class 18: ipc_ex/18_class.md
    - Class 19: ipc_ex/19_class.md
    - Class 20: ipc_ex/20_class.md
    - Class 21: ipc_ex/21_class.md
    - Class 22: ipc_ex/22_class.md
    - Class 23: ipc_ex/23_class.md
    - Class 24: ipc_ex/24_class.md
    - Class 25: ipc_ex/25_class.md
    - Class 26: ipc_ex/26_class.md
    - Class 27: ipc_ex/27_class.md
    - Class 28: ipc_ex/28_class.md
    - Class 29: ipc_ex/29_class.md
  - Answer Keys:
    - Index: ipc_key/index.md
    - Class 16 Exercises: ipc_key/16_class.md
    - Class 17 Exercises: ipc_key/17_class.md
    - Class 18 Exercises: ipc_key/18_class.md
    - Class 19 Exercises: ipc_key/19_class.md
    - Class 20 Exercises: ipc_key/20_class.md
    - Class 21 Exercises: ipc_key/21_class.md
    - Class 22 Exercises: ipc_key/22_class.md
    - Class 23 Exercises: ipc_key/23_class.md
    - Class 24 Exercises: ipc_key/24_class.md
    - Class 25 Exercises: ipc_key/25_class.md
    - Class 26 Exercises: ipc_key/26_class.md
    - Class 27 Exercises: ipc_key/27_class.md
    - Class 28 Exercises: ipc_key/28_class.md
    - Class 29 Exercises: ipc_key/29_class.md
plugins:
- search
